### ISSUE TITLE
Showhealth Plugin doesn't work

### ISSUE THREAD

**Issue by licancharlie** [Daimyo21/Insurgency-dy-sourcemod#28]
Hey Daymyo!
I love all of your plugins and mods.They are really awesome!
I run a server with your mods and plugins. But the showhealth plugin does not work. Can I have some help?In concole, it said showhealth.smx (Show Health): Required extension "Client Preferences" file("clientprefs.ext") not running

But I have the clientprefs.exf file in the extension file.

Best Wishes
Quick_Reborn

**Comment by ozzygit** [comment]
Hi Quick_Reborn, I thought I'd help you out so you probably get a faster response. Client Prefs is part of SourceMod itself and not Daimyo's plugins. If you look at your original sourcemod files (or you could download again) you should see it there and just need to copy it into the extensions folder. It will probably be either clientprefs.ext.so (linux) or clientprefs.ext.dll (I think) for windows.

**Comment by licancharlie** [comment]
Thx for reply me!
It fixed now!
But I met another question, sorry for wasting your time.
I ran a server with Sernix mod. It's really amazing!
It worked fine yesterday, but it ran glitched today.
The character models are in blue errorr. We all miss this fantastic mod :octocat: 
Can I have some help?

Best Wishes
Quick_Reborn

**Comment by ozzygit** [comment]
Are you using a custom theater? If so, where did the theater come from? Does it happen without the custom theater? Is it a custom map? What if you use a standard map?

It sounds like you're using a custom theater, and it's not applying the models correctly.

**Comment by licancharlie** [comment]
Yes, Im using the custom theater (daimyo_gnalvl_theater_v1.0) with the srnx_asset_mods. I put the subscribe IDs into the subscribed_file_ids.txt. I have tried to remove this custom theater, then players can see the enemies without the blue errors. No, it happens on the official map(burihz).
Thanks again! 
So how can I apply the models correctly?

**Comment by licancharlie** [comment]
Oh thx I just fixed it. Change the sv_pure from -1 to 0 and the models applying correctly!
Thx again!
