### ISSUE TITLE
Error loading Medic Plugin

### ISSUE THREAD

**Issue by OlliC** [Daimyo21/Insurgency-dy-sourcemod#33]
Hey, 

so i am trying to get The Armory: Expanded - 35 Angry Bots with Medic Support working on a linux server.
What i have found out so far is that the sourcemod plugin "c_dy_respawn_naong_ai_director" is needed. I managed to compile it by getting all required includes one by one. 

Includes i copied over: 
updater.inc
smlib.inc
smlib/*
loghelper.inc
insurgencydy.inc
insurgency_ad.inc

But then when trying to load it it says: 

`c_dy_respawn_naong_ai_director.smx ([INS] Player Respawn): Native "Ins_ObjectiveResource_GetProp" was not found`

What am i missing?

**Comment by thecannons** [comment]
Looks like a long standing error from original plugin: https://github.com/jaredballou/insurgency-sourcemod/issues/36

If it doesn't cause any issues I'd say ignore it.

**Comment by OlliC** [comment]
I would ignore it, but the problem is it does not get loaded by sourcemod. Maybe i should have made that clearer. 

`sm plugins list` says:
```
18 <Failed> "[INS] Player Respawn" (1.7.0) by Jared Ballou (Contributor: Daimyo, naong, and community members)
Errors:
c_dy_respawn_naong_ai_director.smx ([INS] Player Respawn): Native "Ins_ObjectiveResource_GetProp" was not found

```

**Comment by OlliC** [comment]
Ok what i have found out so far is that insurgency.sp (insurgency.smx) is a requirement for the respawn plugin, because it contains the 'Ins_ObjectiveResource_GetProp' function. So i must be loaded first. 

Now i get this error from loading c_dy_respawn_naong_ai_director.smx:

```
L 12/04/2019 - 09:49:15: [SM] Exception reported: Fatal Error: Unable to find signature for "ForceRespawn"!
L 12/04/2019 - 09:49:15: [SM] Blaming: c_dy_respawn_naong_ai_director.smx
L 12/04/2019 - 09:49:15: [SM] Call stack trace:
L 12/04/2019 - 09:49:15: [SM]   [0] SetFailState
L 12/04/2019 - 09:49:15: [SM]   [1] Line 1027, c_dy_respawn_naong_ai_director.sp::OnPluginStart
```

I am working my way slowly through it :)

Edit: Config file gamedata/plugin.respawn.txt was missing. Now both plugins are loading!
