### ISSUE TITLE
How to disable Ambushes?

### ISSUE THREAD

**Issue by OlliC** [Daimyo21/Insurgency-dy-sourcemod#35]
Hi, 

i am using the plugin "c_dy_respawn_naong_ai_director.smx" for medic support on my armory expanded 35 angry bots server. It does alot more stuff than just medic with jammers, vips, etc.. 
I have disabled this for now with the config (respawn.cfg). But i could not find a switch to disable the ambushes that happen randomly and normally kill everybody on the server within a second. 

What i have tried so far is setting "g_AIDir_AmbushCond_Chance" to 0 in line 105.
https://github.com/Daimyo21/Insurgency-dy-sourcemod/blob/594f5d321010da16cc0ad78478921af4d80cfa80/scripting/c_dy_respawn_naong_ai_director.sp#L105 
And also set "new tAmbushChance = 0" in line 7629. 
https://github.com/Daimyo21/Insurgency-dy-sourcemod/blob/594f5d321010da16cc0ad78478921af4d80cfa80/scripting/c_dy_respawn_naong_ai_director.sp#L7629

But this seem to make no difference. Do you have any hint for me?

**Comment by NullifidianSF** [comment]
Try https://pastebin.com/raw/eDwfFHDb

**Comment by OlliC** [comment]
That seems to do the trick. Thanks.
